# -*- coding: utf-8 -*-
"""nnfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Cbuomcgflf75inSqcCKVTEmMELma4wP
"""

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score


df = pd.read_csv("/content/Housing.csv")
print(df.isnull().sum())
binary_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
for col in binary_cols:
    df[col] = df[col].map({'yes': 1, 'no': 0})

df['furnishingstatus'] = df['furnishingstatus'].map({'unfurnished': 0, 'semi-furnished': 1, 'furnished': 2})

X = df.drop('price', axis=1).values
y = df['price'].values.reshape(-1, 1) / 1_000_000

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)

X_train = torch.FloatTensor(X_train)
y_train = torch.FloatTensor(y_train)
X_val   = torch.FloatTensor(X_val)
y_val   = torch.FloatTensor(y_val)
X_test  = torch.FloatTensor(X_test)
y_test  = torch.FloatTensor(y_test)

# (Experiment 1) ReLU, hidden=[64, 32], lr=0.01

model1 = nn.Sequential(
    nn.Linear(12, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(0.2),
    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.ReLU(),
    nn.Dropout(0.2),
    nn.Linear(32, 1)
)

optimizer1 = optim.Adam(model1.parameters(), lr=0.01)
criterion  = nn.MSELoss()
scheduler1 = optim.lr_scheduler.StepLR(optimizer1, step_size=50, gamma=0.5)

train_losses1, val_losses1 = [], []

for epoch in range(200):
    model1.train()
    output = model1(X_train)
    loss   = criterion(output, y_train)
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()
    scheduler1.step()

    model1.eval()
    with torch.no_grad():
        val_output = model1(X_val)
        val_loss   = criterion(val_output, y_val)

    train_losses1.append(loss.item())
    val_losses1.append(val_loss.item())

    if (epoch + 1) % 50 == 0:
        print(f"Exp1 | Epoch {epoch+1} | Train Loss: {loss.item():.4f} | Val Loss: {val_loss.item():.4f}")

# (Experiment 2 )Tanh, hidden=[128, 64, 32], lr=0.001
model2 = nn.Sequential(
    nn.Linear(12, 128),
    nn.BatchNorm1d(128),
    nn.Tanh(),
    nn.Dropout(0.2),
    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.Tanh(),
    nn.Dropout(0.2),
    nn.Linear(64, 32),
    nn.BatchNorm1d(32),
    nn.Tanh(),
    nn.Dropout(0.2),
    nn.Linear(32, 1)
)

optimizer2 = optim.Adam(model2.parameters(), lr=0.001)
scheduler2 = optim.lr_scheduler.StepLR(optimizer2, step_size=50, gamma=0.5)

train_losses2, val_losses2 = [], []

for epoch in range(200):
    model2.train()
    output = model2(X_train)
    loss   = criterion(output, y_train)
    optimizer2.zero_grad()
    loss.backward()
    optimizer2.step()
    scheduler2.step()

    model2.eval()
    with torch.no_grad():
        val_output = model2(X_val)
        val_loss   = criterion(val_output, y_val)

    train_losses2.append(loss.item())
    val_losses2.append(val_loss.item())

    if (epoch + 1) % 50 == 0:
        print(f"Exp2 | Epoch {epoch+1} | Train Loss: {loss.item():.4f} | Val Loss: {val_loss.item():.4f}")
# Experiment 3
# ReLU, hidden=[128, 64], lr=0.007

model3 = nn.Sequential(
    nn.Linear(12, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(0.1),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(0.05),

    nn.Linear(64, 1)
)

optimizer3 = optim.Adam(model3.parameters(), lr=0.003)

scheduler3 = optim.lr_scheduler.StepLR(
    optimizer3,
    step_size=50,
    gamma=0.5
)

train_losses3 = []
val_losses3   = []

for epoch in range(300):

    model3.train()

    output = model3(X_train)

    loss = criterion(output, y_train)

    optimizer3.zero_grad()

    loss.backward()

    optimizer3.step()

    scheduler3.step()

    model3.eval()

    with torch.no_grad():

        val_output = model3(X_val)

        val_loss = criterion(val_output, y_val)

    train_losses3.append(loss.item())

    val_losses3.append(val_loss.item())

    if (epoch + 1) % 50 == 0:

        print(f"Exp3 | Epoch {epoch+1} | Train Loss: {loss.item():.4f} | Val Loss: {val_loss.item():.4f}")



experiments = [
    ("Exp1 (ReLU, lr=0.01)", model1, train_losses1, val_losses1),
    ("Exp2 (Tanh, lr=0.001)", model2, train_losses2, val_losses2),
    ("Exp3 (ReLU, lr=0.003)", model3, train_losses3, val_losses3)
]

for name, model, train_losses, val_losses in experiments:

    model.eval()

    with torch.no_grad():

        preds = model(X_test)

        mse = criterion(preds, y_test).item()

        preds_np = preds.numpy()

        y_test_np = y_test.numpy()

        r2 = r2_score(y_test_np, preds_np)

    print(f"\n{name}")

    print(f"Final Train Loss : {train_losses[-1]:.4f}")

    print(f"Final Val Loss   : {val_losses[-1]:.4f}")

    print(f"Test MSE         : {mse:.4f}")

    print(f"R² Score         : {r2:.4f}")



plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(train_losses1, label="Train Loss")
plt.plot(val_losses1,   label="Val Loss")
plt.title("(Exp1) ReLU - lr=0.01 - [64, 32]")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(train_losses2, label="Train Loss")
plt.plot(val_losses2,   label="Val Loss")
plt.title("(Exp2) Tanh - lr=0.001 - [128, 64, 32]")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.legend()

plt.tight_layout()
plt.show()


model3.eval()

with torch.no_grad():

    preds = model3(X_test).numpy()

    actual = y_test.numpy()

plt.figure(figsize=(6,6))

plt.scatter(actual, preds)

plt.xlabel("Actual Prices")

plt.ylabel("Predicted Prices")

plt.title("Actual vs Predicted (Experiment 3)")

plt.show()